openapi: 3.2.0
info:
    title: Collaborative Knowledge Platform Backenk service
    description: |4-
        	API for backend service powering Kollap platform.
        	
    version: "1.0"
servers:
    - url: http://localhost:80
      name: kollap
      description: Default server for kollap
paths:
    /v1/documents:
        post:
            tags:
                - documents
            summary: createDocument documents
            operationId: documents#createDocument
            requestBody:
                description: Request body for createDocument.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateDocumentRequestBody'
                        example:
                            content: Exercitationem odit natus consequuntur doloremque.
                            title: Voluptate et nihil quaerat sit error.
                            workspace_id: 0d5ff728-d37a-412b-8864-6ec621221ec2
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Document'
                            example:
                                content: Non ex sit est.
                                created_at: "1999-03-24T10:14:21Z"
                                id: 49608291-1048-4048-95f9-fba0f1509dde
                                title: Quaerat adipisci.
                                version: 2106560497393310639
                                workspace_id: b3e504d0-5995-4ce8-bb47-7a1dca3a94fc
    /v1/documents/{id}:
        get:
            tags:
                - documents
            summary: getDocument documents
            operationId: documents#getDocument
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: 8c7dabda-b24d-4484-9199-df8f98d6d854
                    format: uuid
                  example: 9b1b6de0-efc8-475c-92f8-15c3537edf65
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Document'
                            example:
                                content: Tempora voluptatem qui eius ipsam.
                                created_at: "1970-05-13T09:37:10Z"
                                id: d00088da-f935-4c13-a4ae-1d37c5d95e09
                                title: Qui nobis sunt.
                                version: 776250283615509095
                                workspace_id: ca16f238-c971-4891-b831-a5af3d50c2c8
    /v1/workspaces:
        post:
            tags:
                - workspaces
            summary: createWorkspace workspaces
            operationId: workspaces#createWorkspace
            requestBody:
                description: Request body for createWorkspace.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateWorkspaceRequestBody'
                        example:
                            name: Voluptatem corporis nemo qui dicta occaecati.
                            owner_id: 27bd44a5-6cf6-4e18-8b6b-ae8e809b4337
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Workspace'
                            example:
                                created_at: "1997-02-12T09:49:59Z"
                                id: 72ea645c-b5d8-414b-a9ef-50a95d381edf
                                name: Eum quo incidunt.
                                owner_id: 11e6c044-e250-4055-81fd-ba9bfda9b8df
    /v1/workspaces/{id}:
        get:
            tags:
                - workspaces
            summary: getWorkspace workspaces
            operationId: workspaces#getWorkspace
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: c5bc20db-2876-4778-8f5f-0ef8ae756ca8
                    format: uuid
                  example: 07374633-fdc6-43cb-9b5d-b819f19b8c5a
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Workspace'
                            example:
                                created_at: "1977-04-10T21:47:11Z"
                                id: 1907915f-ad48-4af9-ad7e-a0af764c6524
                                name: Eveniet voluptates aut doloremque.
                                owner_id: c11d358a-e860-4bec-9554-68e97bd82838
    /v1/workspaces/{id}/documents:
        get:
            tags:
                - workspaces
            summary: getAllWorkspaceDocuments workspaces
            operationId: workspaces#getAllWorkspaceDocuments
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: d97cc60b-231e-480c-bfb2-efbc1d17d39c
                    format: uuid
                  example: 70e6ef25-05a4-4a66-9516-128fa308ae8d
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetAllWorkspaceDocumentsResponseBody'
                            example:
                                documents:
                                    - content: Quia commodi.
                                      created_at: "2009-05-22T20:22:24Z"
                                      id: f03de107-ca95-4f36-9f62-9679f6271d84
                                      title: Est nihil et quasi molestias.
                                      version: 5981053160314408447
                                      workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
                                    - content: Quia commodi.
                                      created_at: "2009-05-22T20:22:24Z"
                                      id: f03de107-ca95-4f36-9f62-9679f6271d84
                                      title: Est nihil et quasi molestias.
                                      version: 5981053160314408447
                                      workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
                                    - content: Quia commodi.
                                      created_at: "2009-05-22T20:22:24Z"
                                      id: f03de107-ca95-4f36-9f62-9679f6271d84
                                      title: Est nihil et quasi molestias.
                                      version: 5981053160314408447
                                      workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
components:
    schemas:
        CreateDocumentRequestBody:
            type: object
            properties:
                content:
                    type: string
                    example: Exercitationem odit natus consequuntur doloremque.
                title:
                    type: string
                    example: Voluptate et nihil quaerat sit error.
                workspace_id:
                    type: string
                    example: 0d5ff728-d37a-412b-8864-6ec621221ec2
                    format: uuid
            description: Request body for createDocument.
            example:
                content: Exercitationem odit natus consequuntur doloremque.
                title: Voluptate et nihil quaerat sit error.
                workspace_id: 0d5ff728-d37a-412b-8864-6ec621221ec2
            required:
                - title
                - workspace_id
        CreateWorkspaceRequestBody:
            type: object
            properties:
                name:
                    type: string
                    example: Voluptatem corporis nemo qui dicta occaecati.
                owner_id:
                    type: string
                    example: 27bd44a5-6cf6-4e18-8b6b-ae8e809b4337
                    format: uuid
            description: Request body for createWorkspace.
            example:
                name: Voluptatem corporis nemo qui dicta occaecati.
                owner_id: 27bd44a5-6cf6-4e18-8b6b-ae8e809b4337
            required:
                - name
                - owner_id
        Document:
            type: object
            properties:
                content:
                    type: string
                    example: Quia commodi.
                created_at:
                    type: string
                    example: "2009-05-22T20:22:24Z"
                    format: date-time
                id:
                    type: string
                    example: f03de107-ca95-4f36-9f62-9679f6271d84
                    format: uuid
                title:
                    type: string
                    example: Est nihil et quasi molestias.
                version:
                    type: integer
                    example: 5981053160314408447
                    format: int64
                workspace_id:
                    type: string
                    example: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
                    format: uuid
            description: Knowledge sharing medium in this platform is a document.
            example:
                content: Quia commodi.
                created_at: "2009-05-22T20:22:24Z"
                id: f03de107-ca95-4f36-9f62-9679f6271d84
                title: Est nihil et quasi molestias.
                version: 5981053160314408447
                workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
            required:
                - id
                - title
                - version
                - content
                - workspace_id
                - created_at
        GetAllWorkspaceDocumentsResponseBody:
            type: object
            properties:
                documents:
                    type: array
                    items:
                        $ref: '#/components/schemas/Document'
                    example:
                        - content: Quia commodi.
                          created_at: "2009-05-22T20:22:24Z"
                          id: f03de107-ca95-4f36-9f62-9679f6271d84
                          title: Est nihil et quasi molestias.
                          version: 5981053160314408447
                          workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
                        - content: Quia commodi.
                          created_at: "2009-05-22T20:22:24Z"
                          id: f03de107-ca95-4f36-9f62-9679f6271d84
                          title: Est nihil et quasi molestias.
                          version: 5981053160314408447
                          workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
                        - content: Quia commodi.
                          created_at: "2009-05-22T20:22:24Z"
                          id: f03de107-ca95-4f36-9f62-9679f6271d84
                          title: Est nihil et quasi molestias.
                          version: 5981053160314408447
                          workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
            example:
                documents:
                    - content: Quia commodi.
                      created_at: "2009-05-22T20:22:24Z"
                      id: f03de107-ca95-4f36-9f62-9679f6271d84
                      title: Est nihil et quasi molestias.
                      version: 5981053160314408447
                      workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
                    - content: Quia commodi.
                      created_at: "2009-05-22T20:22:24Z"
                      id: f03de107-ca95-4f36-9f62-9679f6271d84
                      title: Est nihil et quasi molestias.
                      version: 5981053160314408447
                      workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
                    - content: Quia commodi.
                      created_at: "2009-05-22T20:22:24Z"
                      id: f03de107-ca95-4f36-9f62-9679f6271d84
                      title: Est nihil et quasi molestias.
                      version: 5981053160314408447
                      workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
        Workspace:
            type: object
            properties:
                created_at:
                    type: string
                    example: "1997-02-12T09:49:59Z"
                    format: date-time
                id:
                    type: string
                    example: 72ea645c-b5d8-414b-a9ef-50a95d381edf
                    format: uuid
                name:
                    type: string
                    example: Eum quo incidunt.
                owner_id:
                    type: string
                    example: 11e6c044-e250-4055-81fd-ba9bfda9b8df
                    format: uuid
            description: Workspace is where multiple people can come and share knowledge using documents.
            example:
                created_at: "1997-02-12T09:49:59Z"
                id: 72ea645c-b5d8-414b-a9ef-50a95d381edf
                name: Eum quo incidunt.
                owner_id: 11e6c044-e250-4055-81fd-ba9bfda9b8df
            required:
                - id
                - name
                - owner_id
                - created_at
tags:
    - name: workspaces
      description: Workspaces related requests
    - name: documents
      description: Documents related Endpoints
